-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 20:20:58 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eLearningProject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eLearningProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eLearningProject` DEFAULT CHARACTER SET utf8 COLLATE utf8_turkish_ci ;
USE `eLearningProject` ;

-- -----------------------------------------------------
-- Table `eLearningProject`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(50) NULL,
  `createdDate` DATETIME NULL,
  `updatedDate` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`catagories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`catagories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `instructorId` INT NULL,
  `catagoryId` INT NULL,
  `price` VARCHAR(10) NULL,
  `createdDate` DATETIME NULL,
  `updatedDate` DATETIME NULL,
  `isActive` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fCatagoryId_idx` (`catagoryId` ASC),
  INDEX `fInstructorId_idx` (`instructorId` ASC),
  CONSTRAINT `fCatagoryId_courses`
    FOREIGN KEY (`catagoryId`)
    REFERENCES `eLearningProject`.`catagories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fInstructorId_courses`
    FOREIGN KEY (`instructorId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`chapters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `no` INT NULL,
  `courseId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fCourseId_idx` (`courseId` ASC),
  CONSTRAINT `fCourseId_chapters`
    FOREIGN KEY (`courseId`)
    REFERENCES `eLearningProject`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`courseDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`courseDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courseId` INT NULL,
  `summary` VARCHAR(1000) NULL,
  `objectives` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`),
  INDEX `fCourseId_idx` (`courseId` ASC),
  CONSTRAINT `fCourseId_courseDetails`
    FOREIGN KEY (`courseId`)
    REFERENCES `eLearningProject`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`courseToUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`courseToUser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courseId` INT NULL,
  `userId` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fUserId_idx` (`userId` ASC),
  INDEX `fCourseId_idx` (`courseId` ASC),
  CONSTRAINT `fCourseId_c2u`
    FOREIGN KEY (`courseId`)
    REFERENCES `eLearningProject`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fUserId_c2u`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`educationLevels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`educationLevels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`lessonLegends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`lessonLegends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`documentTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`documentTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chapterId` INT NULL,
  `name` VARCHAR(200) NULL,
  `duration` VARCHAR(10) NULL,
  `typeId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fChapterId_idx` (`chapterId` ASC),
  INDEX `fLessonTypeId_idx` (`typeId` ASC),
  CONSTRAINT `fLessonTypeId_lessons`
    FOREIGN KEY (`typeId`)
    REFERENCES `eLearningProject`.`documentTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fChapterId_lessons`
    FOREIGN KEY (`chapterId`)
    REFERENCES `eLearningProject`.`chapters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`lessonProgress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`lessonProgress` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `lessonId` INT NULL,
  `lessonLegendId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fLessenLegendId_idx` (`lessonLegendId` ASC),
  INDEX `fLessonId_idx` (`lessonId` ASC),
  INDEX `fUserId_idx` (`userId` ASC),
  CONSTRAINT `fUserId_lessonProgress`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fLessonId_lessonProgress`
    FOREIGN KEY (`lessonId`)
    REFERENCES `eLearningProject`.`lessons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fLessenLegendId_lessonProgress`
    FOREIGN KEY (`lessonLegendId`)
    REFERENCES `eLearningProject`.`lessonLegends` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`occupations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`occupations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`paymentProcess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`paymentProcess` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `courseId` INT NULL,
  `situation` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fCourseId_idx` (`courseId` ASC),
  INDEX `fUserId_idx` (`userId` ASC),
  CONSTRAINT `fUserId_paymentProcess`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fCourseId_paymentProcess`
    FOREIGN KEY (`courseId`)
    REFERENCES `eLearningProject`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`userTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`userTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courseId` INT NULL,
  `stars` VARCHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fCourseId_idx` (`courseId` ASC),
  CONSTRAINT `fCourseId_ratings`
    FOREIGN KEY (`courseId`)
    REFERENCES `eLearningProject`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`examTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`examTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`examProcess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`examProcess` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `chapterId` INT NULL,
  `isSuccess` INT NULL,
  `Grade` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `ChapterId_idx` (`chapterId` ASC),
  INDEX `fUserId_idx` (`userId` ASC),
  CONSTRAINT `fUserId_examProcess`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ChapterId_examProcess`
    FOREIGN KEY (`chapterId`)
    REFERENCES `eLearningProject`.`chapters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`documents` (
  `id` INT NOT NULL,
  `documentTypeId` INT NULL,
  `courseId` INT NULL,
  `lessonId` INT NULL,
  `createdDate` DATETIME NULL,
  `uploadedDate` DATETIME NULL,
  `explanation` VARCHAR(300) NULL,
  `name` VARCHAR(200) NULL,
  `isAsset` INT NULL DEFAULT 0,
  INDEX `fLessonId_idx` (`lessonId` ASC),
  PRIMARY KEY (`id`),
  INDEX `fDocumentTypeId_idx` (`documentTypeId` ASC),
  INDEX `fCourseId_doc_idx` (`courseId` ASC),
  CONSTRAINT `fLessonId_doc`
    FOREIGN KEY (`lessonId`)
    REFERENCES `eLearningProject`.`lessons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fDocumentTypeId_doc`
    FOREIGN KEY (`documentTypeId`)
    REFERENCES `eLearningProject`.`documentTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fCourseId_doc`
    FOREIGN KEY (`courseId`)
    REFERENCES `eLearningProject`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`userDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`userDetails` (
  `userId` INT NULL,
  `age` VARCHAR(2) NULL,
  `phone` VARCHAR(15) NULL,
  `typeId` INT NULL,
  `occupationId` INT NULL,
  `educationId` INT NULL,
  `fbUserName` VARCHAR(45) NULL,
  `twUserName` VARCHAR(45) NULL,
  `about` VARCHAR(1000) NULL,
  `profileImageURL` VARCHAR(200) NULL,
  `tcNo` VARCHAR(11) NULL,
  `address` VARCHAR(1000) NULL,
  `gender` VARCHAR(1) NULL,
  INDEX `fOccupation_idx` (`occupationId` ASC),
  INDEX `fEducationLevelId_idx` (`educationId` ASC),
  INDEX `fUserId_idx` (`userId` ASC),
  INDEX `fUserTypeId_idx` (`typeId` ASC),
  CONSTRAINT `fOccupationId_uD`
    FOREIGN KEY (`occupationId`)
    REFERENCES `eLearningProject`.`occupations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fEducationLevelId_uD`
    FOREIGN KEY (`educationId`)
    REFERENCES `eLearningProject`.`educationLevels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fUserTypeId_uD`
    FOREIGN KEY (`typeId`)
    REFERENCES `eLearningProject`.`userTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fUserId_uD`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `permission` INT NULL,
  `courseId` INT NULL,
  `createdDate` DATETIME NULL,
  `updatedDate` DATETIME NULL,
  `isActive` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fUserId_idx` (`userId` ASC),
  INDEX `fCourseId_idx` (`courseId` ASC),
  CONSTRAINT `fUserId_comments`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fCourseId_comments`
    FOREIGN KEY (`courseId`)
    REFERENCES `eLearningProject`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`discussions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`discussions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `courseId` INT NULL,
  `title` VARCHAR(45) NULL,
  `createdDate` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fUserId_idx` (`userId` ASC),
  INDEX `fCourseId_idx` (`courseId` ASC),
  CONSTRAINT `fUserId_discussions`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fCourseId_discussions`
    FOREIGN KEY (`courseId`)
    REFERENCES `eLearningProject`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `discussionId` INT NULL,
  `createdDate` VARCHAR(45) NULL,
  `updatedDate` VARCHAR(45) NULL,
  `content` VARCHAR(2000) NULL,
  PRIMARY KEY (`id`),
  INDEX `fUserId_idx` (`userId` ASC),
  INDEX `fDisscussionId_idx` (`discussionId` ASC),
  CONSTRAINT `fUserId_posts`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fDisscussionId_posts`
    FOREIGN KEY (`discussionId`)
    REFERENCES `eLearningProject`.`discussions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(45) NULL,
  `correctAnswer` VARCHAR(45) NULL,
  `duration` INT NULL,
  `examTypeId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fExamTypeId_idx` (`examTypeId` ASC),
  CONSTRAINT `fExamTypeId_questions`
    FOREIGN KEY (`examTypeId`)
    REFERENCES `eLearningProject`.`examTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`exams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questionId` INT NULL,
  `createdDate` DATETIME NULL,
  `updatedDate` DATETIME NULL,
  `InstructorId` INT NULL,
  `chapterId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fInstructorId_idx` (`questionId` ASC),
  INDEX `fChapterId_idx` (`chapterId` ASC),
  CONSTRAINT `fInstructorId_exams`
    FOREIGN KEY (`questionId`)
    REFERENCES `eLearningProject`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fChapterId_exams`
    FOREIGN KEY (`chapterId`)
    REFERENCES `eLearningProject`.`chapters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`universities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`universities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `cityId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fCity_idx` (`cityId` ASC),
  CONSTRAINT `fCity_universities`
    FOREIGN KEY (`cityId`)
    REFERENCES `eLearningProject`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`sems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`sems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `personalName` VARCHAR(45) NULL,
  `personalSurname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `universityId` INT NULL,
  `createdDate` DATETIME NULL,
  `updatedDate` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fUniversity_idx` (`universityId` ASC),
  CONSTRAINT `fUniversity_sems`
    FOREIGN KEY (`universityId`)
    REFERENCES `eLearningProject`.`universities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`views`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`views` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `viewerId` INT NULL,
  `documentId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fViewerId_idx` (`viewerId` ASC),
  INDEX `fDocumentId_idx` (`documentId` ASC),
  CONSTRAINT `fViewerId_v`
    FOREIGN KEY (`viewerId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fDocumentId_v`
    FOREIGN KEY (`documentId`)
    REFERENCES `eLearningProject`.`documents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`IPTables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`IPTables` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `IP` VARCHAR(15) NULL,
  `where` VARCHAR(100) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fUserId_idx` (`userId` ASC),
  CONSTRAINT `fUserId_IP`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`bills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `billNo` VARCHAR(10) NULL,
  `courseId` INT NULL,
  `userId` INT NULL,
  `createdDate` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fUserId_idx` (`userId` ASC),
  INDEX `fCourseId_idx` (`courseId` ASC),
  CONSTRAINT `fUserId_bill`
    FOREIGN KEY (`userId`)
    REFERENCES `eLearningProject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fCourseId_bill`
    FOREIGN KEY (`courseId`)
    REFERENCES `eLearningProject`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eLearningProject`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eLearningProject`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lessonId` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fLessonId_t_idx` (`lessonId` ASC),
  CONSTRAINT `fLessonId_t`
    FOREIGN KEY (`lessonId`)
    REFERENCES `eLearningProject`.`lessons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
